sudo: required

language: python

python:
  - "3.5"

services:
  - docker

before_install:
  - docker --version
  - docker-compose --version
  - docker-compose -f docker-compose-build.yml build
  - docker-compose -f docker-compose-build.yml ps

script:
  - docker-compose -f docker-compose-build.yml run --rm django python manage.py test --failfast

