sudo: required

language: python

python:
  - "3.5"

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - docker --version
  - docker-compose --version
  - docker-compose -f docker-compose-build.yml build
  - docker-compose -f docker-compose-build.yml ps

script:
  - docker-compose -f docker-compose-build.yml run --rm -e DJANGO_SETTINGS_MODULE='config.settings.test' django python manage.py test --failfast

after_success:
  - git clean -fdx
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker build -t $TRAVIS_REPO_SLUG:$COMMIT --build-arg VCS_REF=$COMMIT .;
    docker tag $TRAVIS_REPO_SLUG:$COMMIT $TRAVIS_REPO_SLUG:latest;
    docker tag $TRAVIS_REPO_SLUG:$COMMIT $TRAVIS_REPO_SLUG:travis-$TRAVIS_BUILD_NUMBER;
    docker push $TRAVIS_REPO_SLUG;
    fi

