version: '2'

services:
  postgres:
    build: ./compose/postgres

  redis:
    image: redis:latest

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    environment:
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
