version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  inbox-django-media: {}
  inbox-django-static: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    volumes:
      - inbox-django-static:/app/static
      - inbox-django-media:/app/media
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .env

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    volumes:
      - inbox-django-static:/static
      - inbox-django-media:/media
    ports:
      - "0.0.0.0:80:80"


  redis:
    image: redis:latest

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    env_file: .env
    volumes:
      - inbox-django-media:/app/media
    depends_on:
     - postgres
     - redis
     - clamav
    command: celery -A inbox.taskapp worker -l INFO

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    env_file: .env
    volumes:
      - inbox-django-media:/app/media

    depends_on:
      - postgres
      - redis
      - clamav
    command: celery -A inbox.taskapp beat -l INFO

  clamav:
    build: ./compose/clamav
    ports:
      - "3310:3310"

